[dependencies]
repos = [
    ["Emilia-Systems", "csr.h"],
    ["Emilia-Systems", "extensions.h"],
    ["Emilia-Systems", "qemu_io.h"],
    ["Emilia-Systems", "Makefile"],
    ["Emilia-Systems", "linker.ld"],
]