[dependencies]
repos = [
    ["Scala-Systems", "csr.h"],
    ["Scala-Systems", "extensions.h"],
    ["Scala-Systems", "qemu_dev.h"],
    ["Scala-Systems", "Makefile"],
    ["Scala-Systems", "linker.ld"],
]